## Importing the Packages

In [2]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)

Data Analyst Work
1. Gather
2. Cleaning
3. Preprocessing

After Preprocessing, Data Analyst give out the Data Scientist, they use the machine learning knowledge and makes the Predictive model


## Importing the Data

In [3]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter=';', encoding='latin1')
raw_data_np


array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [5]:
np.isnan(raw_data_np).sum() 

88019

In [6]:
temp_fill= np.nanmax(raw_data_np)+1     # Fill with a value larger than the max ---> produce a scalar value across rows and column ---> axis decide it will scalar or vector
temp_mean= np.nanmean(raw_data_np,axis=0) # Fill with the mean, axis=0 column-wise 


/var/folders/kf/n56cn97x5fn523_123jtsv_40000gn/T/ipykernel_27028/3164491702.py:2: RuntimeWarning: Mean of empty slice
  temp_mean= np.nanmean(raw_data_np,axis=0) # Fill with the mean, axis=0 column-wise


In [7]:
temp_fill 

68616520.0

In [8]:
temp_mean # shows the mean of each column

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [9]:
print(raw_data_np.shape)

(10001, 14)


In [10]:
temp_stat= np.array([np.nanmin(raw_data_np,axis=0),
                    temp_mean,np.nanmax(raw_data_np,axis=0)]) 


/var/folders/kf/n56cn97x5fn523_123jtsv_40000gn/T/ipykernel_27028/1210869362.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stat= np.array([np.nanmin(raw_data_np,axis=0),
/var/folders/kf/n56cn97x5fn523_123jtsv_40000gn/T/ipykernel_27028/1210869362.py:2: RuntimeWarning: All-NaN slice encountered
  temp_mean,np.nanmax(raw_data_np,axis=0)])


In [11]:
temp_stat # 3 arrays -> min,mean,max

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [12]:
temp_mean
print(temp_mean)
np.isnan(temp_mean).sum()

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
         nan         nan         nan         nan         nan     3143.85]


8

> From temp_mean, we can see there <nan.isnan we can see there are 8 columns, with complete None values>
> Columns string represents the column no. of nan values

> columns numeric -> each columns most of the values as numeric
> whereas, columns string -> no numeric values are present all are strings

In [13]:
columns_strings= np.argwhere(np.isnan(temp_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [14]:
columns_numeric = np.argwhere(np.isnan(temp_mean)==False).squeeze()
columns_numeric 

array([ 0,  2,  4,  6,  7, 13])

### Re-importing the Dataset

In [ ]:
> autostrip removes the trailing space of each string in the data
> dtype = data type value of each element in the data. 

In [15]:
loan_data_strings= np.genfromtxt("loan-data.csv", delimiter=';', encoding='latin1',
                                skip_header=1,
                                autostrip=True,
                                usecols=columns_strings,
                                dtype=str)
loan_data_strings 
# loan_data_strings only contains the values which are contain nan values.  

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [16]:
# Define columns_numeric by excluding columns_strings from the total column indices
# temp_fill was the max value
loan_data_numeric = np.genfromtxt("loan-data.csv", delimiter=';', encoding='latin1',
                                  skip_header=1,
                                  autostrip=True,
                                  usecols=columns_numeric,
                                  filling_values=temp_fill)
loan_data_numeric 

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [17]:
# loan_data_numeric doesn't contain any nan values now
np.isnan(loan_data_numeric).sum()   

0

### The Names of the Columns

skip_footer = ignores all the rows after the header

In [18]:
header_full = np.genfromtxt("loan-data.csv", delimiter=';', encoding='latin1',autostrip=True,
                                max_rows=1,
                                dtype=str)
header_full 

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [74]:
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]  

In [20]:
header_strings  

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_numeric  

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

Why checkpoints are required:
-> Places throughout our code where we store a copy of our dataset
-> avoid losing data


In [ ]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable) 
    

In [18]:
checkpoint_test= checkpoint("checkpoint-test=",header_strings, load_data_strings)


In [19]:
np.array_equal(checkpoint_test['data'],load_data_strings)



True

## Manipulating String Columns

In [22]:
header_strings 

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [73]:
header_strings[0]= "Issue_date" 

In [24]:
print(header_strings)
loan_data_strings

# the first column stores the month-year for every account

['Issue_date' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [ ]:
> to get the column index data[rows: columns]
> to access the column one it's '0' index not 1

loan_data_strings[:,0] -->  'will return all the issue dates'


In [25]:
np.unique(loan_data_strings[:,0])  

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [ ]:
# now we all the data is from 2015 so -15 can be removed using the strip function

> To remove the unnecessay Strings
np.chararray.strip(column,'String')

In [26]:
loan_data_strings[:,0] =  np.chararray.strip(loan_data_strings[:,0],"-15")
np.unique(loan_data_strings[:,0])  

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [27]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']) 
 

> In analysis represent month values as integer
> store the data using less memeory
> a more easy to follow order of the months

np.where(condition, x, y)

•x: Values to return where the condition is True.
y : Values to return where the condition is False


In [28]:
for i in range(13):
    loan_data_strings[:,0]= np.where(loan_data_strings[:,0]== months[i], i, loan_data_strings[:,0])

In [29]:
np.unique(loan_data_strings[:,0]) 

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [30]:
header_strings 

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
np.unique(loan_data_strings[:,1]) # the second column stores the account status 

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [32]:
np.unique(loan_data_strings[:,1]).size # Total - 9 Account status 

9

we can use np.where() to assign different number to each one
we need to split all possible values into either groups("good" vs "bad")

In [33]:
status_bad = np.array(['', 'Default', 'Charged Off', 'Late (31-120 days)']) 

np.where(condition, True(value),False(Value))
condition = np.isin(loan_data_strings[:,1],status_bad)
True value = 0
False Value = 1  

In [34]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),0,1)
# if the account status is in the bad status, then 0 else 1 

In [35]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [36]:
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
np.unique (loan_data_strings[:,2]) 

array(['', '36 months', '60 months'], dtype='<U69')

In [ ]:
import pandas as pd
file1= pd.read_csv("loan-data.csv", delimiter=';', encoding='latin1')
file1.head(10)

id issue_d  loan_amnt loan_status  funded_amnt        term int_rate  \
0  48010226  May-15    35000.0     Current      35000.0   36 months    13.33   
1  57693261     NaN    30000.0     Current      30000.0   36 months   þëè.89   
2  59432726  Sep-15    15000.0     Current      15000.0   36 months   íîå.53   
3  53222800  Jul-15     9600.0     Current       9600.0   36 months   þëè.89   
4  57803010  Aug-15     8075.0     Current       8075.0   36 months    19.19   
5  63398019  Oct-15    14400.0     Current      14400.0   60 months    13.99   
6  60850626  Sep-15        NaN     Current      13000.0   60 months    24.99   
7  46816139  Apr-15     7500.0     Current       7500.0   36 months    13.33   
8  63918356  Nov-15     8000.0     Current       8000.0   36 months   þëè.89   
9  63651616  Nov-15     7200.0     Current       7200.0   36 months   äåê.59   

  installment grade sub_grade verification_status  \
0     1184.86     C        C3            Verified   
1      938.57     A        A5     Source Verified   
2      494.86     B        B5            Verified   
3      300.35     A        A5        Not Verified   
4      296.78   NaN        E3     Source Verified   
5      334.99   NaN        C4        Not Verified   
6       381.5     F        F4     Source Verified   
7       253.9     C        C3                 NaN   
8      250.29     A        A5     Source Verified   
9      241.18     C        C2                 NaN   

                                                 url addr_state  total_pymnt  
0  https://www.lendingclub.com/browse/loanDetail....         CA      9452.96  
1  https://www.lendingclub.com/browse/loanDetail....         NY      4679.70  
2  https://www.lendingclub.com/browse/loanDetail....         PA      1969.83  
3  https://www.lendingclub.com/browse/loanDetail....         OH      1793.68  
4  https://www.lendingclub.com/browse/loanDetail....         TX      1178.51  
5  https://www.lendingclub.com/browse/loanDetail....         AL       681.17  
6  https://www.lendingclub.com/browse/loanDetail....         CA      1126.45  
7  https://www.lendingclub.com/browse/loanDetail....         GA      2025.65  
8  https://www.lendingclub.com/browse/loanDetail....         MA       497.07  
9  https://www.lendingclub.com/browse/loanDetail....         TX       512.57

Numpy Doesn't support "inplace=True'

In [39]:
loan_data_strings[:,2]= np.chararray.strip(loan_data_strings[:,2]," months")
loan_data_strings[:,2] 

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [40]:
loan_data_strings[:,2]= np.where(loan_data_strings[:,2] == '','60',loan_data_strings[:,2])
loan_data_strings[:,2] 
# remove the months from the column and replace empty values with 60

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [41]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [42]:
# make the name of the column more readable
header_strings[2] = "Term_months"
 

### Grade and Subgrade

In [43]:
header_strings 

array(['Issue_date', 'loan_status', 'Term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [44]:
np.unique(loan_data_strings[:,3])   

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [45]:
np.unique(loan_data_strings[:,4])  

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [46]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])



In [47]:
np.unique(loan_data_strings[:,4], return_counts= True) 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [48]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                    'H1', loan_data_strings[:,4]) 

In [49]:
np.unique(loan_data_strings[:,4]) 

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

Across column 1 

In [50]:
loan_data_strings= np.delete(loan_data_strings,3,axis=1) 
# removed the grade column

In [51]:
loan_data_strings[:,3] 

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [52]:
header_strings = np.delete(header_strings,3)
header_strings[3] 
# confims that grade column is removed

'sub_grade'

#### Converting Sub Grade

In [53]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [55]:
keys = list(np.unique(loan_data_strings[:,3]))                         
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [120]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [121]:
# Convert all subgrades in column 3 to their corresponding integer values using dict_sub_grade
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]= np.where(loan_data_strings[:,3]==i, dict_sub_grade[i], loan_data_strings[:,3])
    

In [122]:
np.unique(loan_data_strings[:,3])



array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [58]:
header_strings 



array(['Issue_date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [63]:
col_copy = loan_data_strings[:,4].copy()

Verified and Source Verified are kind of same --> they can be combines
Two Options:
1) Verfied : Verified, Source Verified -> 1 
2) Source Verified : Not verified , " " -> 0

In [67]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4]=='')|(loan_data_strings[:,4]=='Not Verified'),0,1)


In [68]:
np.unique(loan_data_strings[:,4])



array(['0', '1'], dtype='<U69')

### URL

In [69]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [ ]:
# remove the unnecessary text
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_strings[:,5]                                                              


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [72]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

'id' columns contains the same ID in URL 

In [80]:
loan_data_numeric[:,0].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [81]:
loan_data_strings[:,5].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [82]:
# Confirming that these columns are identical
np.array_equal(loan_data_numeric[:,0].astype(dtype=int), loan_data_strings[:,5].astype(dtype=int))


True

In [ ]:
# url doesn't contain any useful information so we can remove it, as ID- column 1 has the same information
loan_data_strings= np.delete(loan_data_strings,5,axis=1)
header_strings = np.delete(header_strings,5)
header_strings



array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'addr_state'], dtype='<U19')

In [99]:
loan_data_strings = np.delete(loan_data_strings,5,axis=1)


In [92]:
header_numeric


array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### State Address

In [95]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'state_address'], dtype='<U19')

In [94]:
header_strings[5] = "state_address"


In [100]:
np.unique(loan_data_strings[:,5]).size

50

In [101]:
loan_data_strings[:,5]


array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [104]:
states_names,states_count = np.unique(loan_data_strings[:,5], return_counts=True)
states_count_sorted = np.argsort(states_count)[::-1] # In descending Order
states_names[states_count_sorted],states_count[states_count_sorted] 

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KS',
        'KY', 'OK', 'AR', 'UT', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [107]:
# filling out the missing values with the most frequent state
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                    0,
                                    loan_data_strings[:,5])



In [109]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])


https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [ ]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])



In [111]:
np.unique(loan_data_strings[:,5])


array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [123]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [125]:
loan_data_strings = loan_data_strings.astype(dtype=int)
loan_data_strings



array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [ ]:
checkpoint_strings = checkpoint("Checkpoint-Strings",header_strings, loan_data_strings)

In [78]:
checkpoint_strings["header"]


array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [79]:
# check if the data match with out pre-proceessed data
checkpoint_strings["data"]

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '1', '3']], dtype='<U69')

In [ ]:
np.array_equal(checkpoint_strings["data"], loan_data_strings)

True

## Manipulating Numeric Columns

In [127]:
loan_data_numeric


array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [ ]:
np.isnan(loan_data_numeric).sum()

0

### Substitute "Filler" Values

In [129]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [132]:
temp_fill 

68616520.0

This check if I have filled in missing value or not
> As the result is 0, no filler have been added

In [133]:
np.isin(loan_data_numeric[:,0],temp_fill) 

array([False, False, False, ..., False, False, False])

In [134]:
np.isin(loan_data_numeric[:,0], temp_fill).sum()

0

In [ ]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [135]:
temp_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [136]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [ ]:
# values of min, max, mean are stored in temp_stat
temp_stat[:, columns_numeric] # return only the numeric columns --> Row 1 : temp_min Row 2 : temp_mean Row 3 : temp_max

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [139]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [142]:
# it need to be replaced with minimum value


In [ ]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temp_fill, 
                                  temp_stat[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2] # replaced the fillers with min value 

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [143]:
temp_stat[0,columns_numeric[3]]


6.0

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [92]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [93]:
for i in [1,3,4,5]:
    load_data_numeric[:,i] = np.where(load_data_numeric[:,i]==temp_fill, temp_stat[2,columns_numeric[i]],load_data_numeric[:,i])

### Currency Change

#### The Exchange Rate

In [94]:
EUR_USD= np.genfromtxt("EUR-USD.csv", delimiter=',', encoding='latin1', autostrip=True, skip_header=1,usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [95]:
load_data_strings[:,0]
# value shows in the which month the loan was issued, 0 mean - it's not provided

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [96]:
# Assume the first column of load_data_strings contains month numbers as strings
months_col = load_data_strings[:, 0].astype(int)
exchange_rate = np.zeros_like(months_col, dtype=float)

for i in range(1, 13):
    exchange_rate = np.where(months_col == i, EUR_USD[i-1], exchange_rate)
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [97]:
exchange_rate.shape

(10000,)

In [98]:
load_data_numeric.shape  

(10000, 6)

In [99]:
# setting a new shape to exchange_rate
exchange_rate= np.reshape(exchange_rate,(10000,1))

In [100]:
load_data_numeric = np.hstack((load_data_numeric,exchange_rate))

In [ ]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'exchange_rate'], dtype='<U19')

#### From USD to EUR

In [113]:

# Remove duplicate or extra 'exchange_rate' from header_numeric, keep only the first occurrence
_, idx = np.unique(header_numeric, return_index=True)
header_numeric = header_numeric[np.sort(idx)]
header_numeric

# four of them contain the amount in dollars : loan_amnt, funded_amnt, installment, total_pymnt
# four of them contain the amount in dollars : loan_amnt, funded_amnt, installment, total_pymnt

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [103]:
columns_dollar = np.array([1,2,4,5])

In [104]:
load_data_numeric[:,[columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [105]:
# accessing the exchange rate
load_data_numeric[:,6]

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

Add the Euro versio of money using Loop

In [106]:
for i in columns_dollar:
    load_data_numeric = np.hstack((load_data_numeric, np.reshape(load_data_numeric[:,i] / load_data_numeric[:,6], (10000,1))))
    

/var/folders/kf/n56cn97x5fn523_123jtsv_40000gn/T/ipykernel_6782/2354205804.py:2: RuntimeWarning: divide by zero encountered in divide
  load_data_numeric = np.hstack((load_data_numeric, np.reshape(load_data_numeric[:,i] / load_data_numeric[:,6], (10000,1))))
/var/folders/kf/n56cn97x5fn523_123jtsv_40000gn/T/ipykernel_6782/2354205804.py:2: RuntimeWarning: invalid value encountered in divide
  load_data_numeric = np.hstack((load_data_numeric, np.reshape(load_data_numeric[:,i] / load_data_numeric[:,6], (10000,1))))


In [108]:
load_data_numeric.shape

(10000, 11)

In [107]:
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,         inf,         inf,         inf],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Expanding the header

In [114]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])


In [115]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [116]:
header_numeric= np.concatenate((header_numeric, header_additional))


In [119]:
header_numeric



array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [120]:
header_numeric[columns_dollar]= np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])
header_numeric


array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [121]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]


In [122]:
header_numeric = header_numeric[columns_index_order]


In [123]:
load_data_numeric


array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,         inf,         inf,         inf],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [124]:
load_data_numeric = load_data_numeric[:,columns_index_order]


### Interest Rate

In [125]:
header_numeric


array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [126]:
load_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [127]:
load_data_numeric[:,5] = load_data_numeric[:,5]/100


In [128]:
load_data_numeric[:,5]


array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [130]:
checkpoint_numeric = checkpoint("checkpoint-Numeric", header_numeric,load_data_numeric)


In [131]:
checkpoint_numeric['header'], checkpoint_numeric['data']


(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,         inf, ...,     4679.7 ,         inf,        0.  ],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [132]:
checkpoint_strings['data'].shape


(10000, 6)

In [133]:
checkpoint_numeric['data'].shape


(10000, 11)

In [ ]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))


array([['48010226.0', '35000.0', '31933.300588066133', ..., '13', '1', '1'],
       ['57693261.0', '30000.0', 'inf', ..., '5', '1', '4'],
       ['59432726.0', '15000.0', '13326.299635729729', ..., '10', '1', '4'],
       ...,
       ['50415990.0', '10000.0', '8910.299817080173', ..., '5', '1', '1'],
       ['46154151.0', '35000.0', '31490.899909678574', ..., '17', '1', '3'],
       ['66055249.0', '10000.0', '9145.799735022167', ..., '4', '1', '3']], dtype='<U69')

In [ ]:
(load_data_strings == '').sum() # check nan values for the string data type

0

In [147]:
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))


## Sorting the New Dataset

In [ ]:
load_data = load_data[np.argsort(load_data[:,0])]


## Storing the New Dataset